keys:
  - &primary age1j3uuyax673fvl5x4dveupq3dylngnrq0e5uy7fmclsexkfd25vysk646wk
creation_rules:
  - path_regex: home-manager/users/(sweetbread|chest)/secrets.yaml$
    key_groups:
      - age:
          - *primary
  - path_regex: nixos/hosts/(Rias|Senko|Eclipse)/secrets/.+$
    key_groups:
      - age:
          - *primary
